### ISSUE TITLE
2D/3D use

### ISSUE THREAD

**Issue by SouthAmericaB** [frankkramer-lab/MIScnn#1]
Hi! 
I would like to know id unet models can be used both in 2d and 3D. 
For example, to use Multires.py with 2D data, would be correct by setting the number of input channels to 1?

Thank you very much!

**Comment by muellerdo** [comment]
Hey  SouthAmericaB,

sadly no. Only the standard U-Net Architecture can be currently used for processing 2D or 3D data. 
The others model architectures are a little bit outdated and can't be used right now. (because they only support 3D models)

If you want the use the Multires model, you have to manually adjust the layers for 2D images and then pass it to the Neural Network class as Architecture.

I'm planning to add an example for how I used MIScnn for the Kidney Tumor Segmentation Challenge. Approximately end of September. 

Greetings,
Dominik

**Comment by muellerdo** [comment]
Todo:
- Update remaining U-Net models in order to be usable as interface for Neural Network class

**Comment by SouthAmericaB** [comment]
All right! Thanks a lot and best regards! :)

**Comment by muellerdo** [comment]
Updated all U-Net models to the new MIScnn architecture standard.
-> They are now all usable 

Usage:
```py
from miscnn.neural_network.model import Neural_Network
from miscnn.neural_network.architecture.unet.multiRes import Architecture

unet_multiRes = Architecture()
model = Neural_Network(preprocessor=pp, architecture=unet_multiRes)
```

The Residual and Dense U-Net variants can be used identically. 
Also, I have tested them both and they work fine :)

Sadly, I haven't found any time, yet, to test out the performance of the MutliRes architecture.
But it runs fine in the MIScnn pipeline and I haven't changed the code for the architecture 
-> it is still the original code from the paper soooo it should work

If you are using it, please share its performance with me :)

Greetings,
Dominik
