### ISSUE TITLE
Patch-wise training question

### ISSUE THREAD

**Issue by MichaelLempart** [frankkramer-lab/MIScnn#14]
Hi,

I got a question regarding patch-wise training. 
If in example a Unet is trained on 3D volumes with a patch size of (64,64,64) and a batch size of 2, it seems that only 2 patches are chosen for training, even though the number of extracted patches is higher.
Now Iam wondering why the network isn't trained with all patches?

Thanks in advance,

Cheers,

Michael

**Comment by MichaelLempart** [comment]
Hi again, 

I noticed that I generated patches 'on the fly' instead of backing up all patches to disk before.
Now it makes sense to me :-)

Cheers,

Michael

**Comment by muellerdo** [comment]
**The following text is a cutout from our email conversation, which is published here for the possibility to be helpful for someone else.**

glad to hear that you are interested in using MIScnn in your research!

Here is some explanation for this behavior:

MIScnn supports two patchwise approaches:
- patchwise-grid: Which splits an image/volume into a list of patches according to the patch & image size
- patchwise-crop: Which randomly crops a single patch from the image

-> patchwise-grid should return multiple patches for a single image
-> patchwise-crop should return only a single patch for a single image

For inference, MIScnn always uses patchwise-grid for any patchwise method. Of course due to we want the segmentation for the complete image.
But why are there two methods for training?

patchwise-grid is the traditional/intuitive way to go for patchwise analysis.
Nevertheless, patchwise-crop approaches are the future and currently state-of-the-art in all medical image challenge winning pipelines.
The data set act more like a variant database in this approach, in which in every iteration a random patch set is pulled from a random image of the data.
After extensive data augmentation, it is possible to create a unique and novel image in every iteration & every epoch. This reduces the risk of overfitting significantly,
which is highly important in medical image analysis (because you will normally have limited data).

> I tried setting the batch size equal to 2 and train on the first 80 cases of the kidney dataset (as in your example).
>
>  
>
> If I know would consider training on whole images, that would mean  40 iterations / steps for each epoch.
>
>  
> When I train on patches though, the number of cases is still 80, though the number of training samples should be much higher. (in example If one would get 64 patches for each volume à 80*64 samples)

With patchwise-crop and a batch size of 2, I would expect that for 80 samples we should obtain 40 iterations.
That is correct.

But with patchwise-grid, I would expect way more. Like you already mentioned, you will get multiple patches out of a single volume.
Therefore, the number of iterations should be way higher.

> If I now run your example with patchwise-grid training on the first 80 cases with a patch shape of (64,64,64), I still get 2 batches only.
> Shouldn’t the network be trained on all patches extracted from one volume?

Yes, it should be. But we have to differ between batch size and iterations. The number of iterations should increase, but the batch size is always fixed on e.g. 2.

If you haven't figured the problem out, yet, I would be happy to have a look in your code,
 so we can get your MIS running on the expected behavior.

Some starting points:
- It is possible to also fix the number of iterations in the model.train() function.
By default, it is None -> The number of iterations equals the standard definition = one run through the complete data set
But for limited data set sizes, it makes sense to run at least 50-100 iterations per epoch. Therefore, MIScnn supports the option to artificially increase the number of iterations.
- I also implemented the patchwise_skip_blanks class variable for the Preprocessor. By default, this is false. But is you manually activate it, all patches with only background as segmentation
will be excluded from the training. This is not recommended, but it can be required in some scenarios.

So super long text.
I hope that I was able to help you.
