### ISSUE TITLE
Error while running example with Dataset from Kits19

### ISSUE THREAD

**Issue by valentinogrean** [frankkramer-lab/MIScnn#5]
Hello and thx for the implementation (it is helpful).

Unfortunately, I encounter an issue when I run the example; more specifically at the model training step

tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 4 must match. Input 1 has shape [2 3 18 18 256] and doesn't match input 0 with shape [2 2 18 18 256].   
         [[{{node training/Adam/gradients/concatenate_1/concat_grad/ConcatOffset}}]]
As stated in the title, I am using the dataset provided in https://github.com/neheller/kits19
Also I am using tensorflow cpu

Thx in advance

**Comment by valentinogrean** [comment]
It might be an issue related to patch shape
For example creating the Preprocessor with patch_shape=(128,128,128) works (as in the example from the main page). Using patch_shape=(80,160,160) as in the Usage page returns error. It is strange, as the dataset sizes are bigger.

**Comment by muellerdo** [comment]
Hey valentinogrean,

sorry for the late response.
Yes, the error arrises because images or patches have to be dividable by 2. This can be explained due to the U-Net architecture (which is used by default in MIScnn) uses MaxPooling layers multiple times which reduces the image sizes by 2.
Example: (128,128,128) -> (64,64,64) -> (32,32,32) ...

Now, the problem can arise that images which are smaller than patch size can't be shrinked by half. (128,128,57) -> (64,64,?)

Right now, a quick but dirty solution would be to use the resize subfunction during the Processing to ensure a working Image size. 

A better solution would be to implement a preprocessing subfunction to pad/fill up images which are smaller than your defined patch shape. 

Still, thanks for the feedback! :)
I will most likely upgrade the patch creation process in order to automatically pad smaller images. The alternative would be that I will add a preprocessing subfunction for image padding that ensures a minimum image size.

I can give you an update in February due to I'm on vacation right now. 

Greetings,
Dominik

**Comment by muellerdo** [comment]
*Added a todo card to implement automatic padding during patch creation on the in-progress column of the MIScnn development board

**Comment by muellerdo** [comment]
One addition, there is a MIScnn example for the KiTS19 data set under Examples in the MIScnn wiki.

**Comment by valentinogrean** [comment]
Thank you for the response. Much appreciated.
