### ISSUE TITLE
no such file or no access

### ISSUE THREAD

**Issue by Mamayuker0** [frankkramer-lab/MIScnn#7]
hi, what you did is awesome and I hope I can implement it to my case but I have some problems, hope you might help

please note I'm new here
1.
I try to run your .ipynb but change a few things according to my case, and raise this error: (in one of the many tracebacks)

FileNotFoundError: No such file or no access: \training\training_sa_crop_pat9.nii\imaging.nii.gz'

after I take a look and the nifti_io.py, I found that in line 84
vol = nib.load(os.path.join(img_path, "imaging.nii.gz"))
why do we need to add imaging.nii.gz? I can't find the easy workaround for this matter

2.
to work with your code properly is there a specific way to structure my directory?
now my directory looks like this:
-project root\
--training\
---training_sa_pat0.nii
---training_sa_pat0-label.nii
and so on.
(for my previous work for this dataset, I manually extract .nii.gz into .nii)

sorry for my English. I appreciate your help

**Comment by muellerdo** [comment]
Heyho Mamayuker0,

thanks for you words. I'm always interested in projects using MIScnn, so if you want to share your experiences or want to contribute an example, you are more than welcome :)

1) and 2):
MIScnn supports dynamic/switchable IO interfaces. The idea behind this is, that you just write your own IO interface for your data set (file structure) instead of forcing your specific data set in a fixed file structure.

The NifTI IO interfaces provided by MIScnn is based on the KiTS19 data set. Therefore, it expects the following data structure:
data/
data/sample_1
data/sample_1/imaging.nii.gz
data/sample_1/segmentation.nii.gz
...
data/sample_200
data/sample_200/imaging.nii.gz
data/sample_200/segmentation.nii.gz

Also due to storage reasons, the NIfTI IO interface expects that the imaging files are all compressed.

Nevertheless, I would recommend that you write your own custom IO interface. 
An IO interface have to inherit the abstract base class Abstract_IO from miscnn.data_loading.interfaces.abstract_io.py. As an example, you can just copy the NIfTI IO interface and modify it for your desired file structure. 

You can read more about IO interfaces in the documentation:
https://github.com/frankkramer-lab/MIScnn/wiki/IO-Interfaces
(which also need a bit more love as soon as I find time for it)

I hope, that I could helped you.
If you have more questions, just open an issue or write me an email. :)

Cheers,
Dominik

**Comment by Mamayuker0** [comment]
dear muellerdo

thank you for your fast and clear response, which explains a lot.
ill make sure if I got prominent result from my case, ill share the experience and example

regards,
Mamayuker0
